[이름 주의] df_DS으로 모든 코드를 바꾸기 힘들어서 df_SJ 그대로 이용

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [3]:
file_dr = 'C:/Users/82108/Desktop/dldusrud/논문집필/데이터분석/'

In [4]:
df_SJ = pd.read_csv(file_dr + '당진_태양광 데이터.csv')

In [5]:
df_SJ

date  temp  rain  wind_speed  humidity  sun_hour  \
0       2015-01-01 1:00  -4.4   0.0         5.4      47.0       0.0   
1       2015-01-01 2:00  -4.6   0.0         4.9      50.0       0.0   
2       2015-01-01 3:00  -4.7   0.0         6.2      50.0       0.0   
3       2015-01-01 4:00  -5.0   0.0         5.0      56.0       0.0   
4       2015-01-01 5:00  -5.0   0.0         5.5      52.0       0.0   
...                 ...   ...   ...         ...       ...       ...   
26298  2017-12-31 19:00   0.9   0.0         2.0      60.0       0.0   
26299  2017-12-31 20:00   0.4   0.0         1.3      63.0       0.0   
26300  2017-12-31 21:00  -1.6   0.0         0.4      72.0       0.0   
26301  2017-12-31 22:00  -1.8   0.0         0.8      78.0       0.0   
26302  2017-12-31 23:00  -2.0   0.0         0.9      72.0       0.0   

       sun_power  snow  cloud  solar_power  
0            0.0   0.5      6          0.0  
1            0.0   0.5      0          0.0  
2            0.0   0.5      6          0.0  
3            0.0   0.5      6          0.0  
4            0.0   0.5      6          0.0  
...          ...   ...    ...          ...  
26298        0.0   0.0      0          0.0  
26299        0.0   0.0      0          0.0  
26300        0.0   0.0      0          0.0  
26301        0.0   0.0      0          0.0  
26302        0.0   0.0      0          0.0  

[26303 rows x 10 columns]

### 결측값 처리하기 (선형보간)

In [6]:
pd.isnull(df_SJ).sum()

date            0
temp            0
rain            0
wind_speed      0
humidity        0
sun_hour        0
sun_power       0
snow            0
cloud           0
solar_power    48
dtype: int64

In [7]:
df_SJ_nonull = df_SJ.interpolate(method = 'linear')

In [8]:
df_SJ_nonull.to_csv(file_dr + '당진_태양광 데이터_결측치처리.csv')

### 결측값 처리 후 데이터 확인

In [9]:
df_SJ = pd.read_csv(file_dr + '당진_태양광 데이터_결측치처리.csv')

In [10]:
df_SJ.head()

Unnamed: 0             date  temp  rain  wind_speed  humidity  sun_hour  \
0           0  2015-01-01 1:00  -4.4   0.0         5.4      47.0       0.0   
1           1  2015-01-01 2:00  -4.6   0.0         4.9      50.0       0.0   
2           2  2015-01-01 3:00  -4.7   0.0         6.2      50.0       0.0   
3           3  2015-01-01 4:00  -5.0   0.0         5.0      56.0       0.0   
4           4  2015-01-01 5:00  -5.0   0.0         5.5      52.0       0.0   

   sun_power  snow  cloud  solar_power  
0        0.0   0.5      6          0.0  
1        0.0   0.5      0          0.0  
2        0.0   0.5      6          0.0  
3        0.0   0.5      6          0.0  
4        0.0   0.5      6          0.0

- date열은 제거

In [11]:
df_SJ = df_SJ.drop(['Unnamed: 0','date'],axis=1)
df_SJ.head()

temp  rain  wind_speed  humidity  sun_hour  sun_power  snow  cloud  \
0  -4.4   0.0         5.4      47.0       0.0        0.0   0.5      6   
1  -4.6   0.0         4.9      50.0       0.0        0.0   0.5      0   
2  -4.7   0.0         6.2      50.0       0.0        0.0   0.5      6   
3  -5.0   0.0         5.0      56.0       0.0        0.0   0.5      6   
4  -5.0   0.0         5.5      52.0       0.0        0.0   0.5      6   

   solar_power  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

### 모든 열의 값이 1인 것 추가 (const)

In [12]:
one = np.ones((df_SJ.shape[0],1))
one = pd.DataFrame(one)

In [13]:
df_SJ1 = pd.concat([one,df_SJ],axis=1)
df_SJ1.head()

0  temp  rain  wind_speed  humidity  sun_hour  sun_power  snow  cloud  \
0  1.0  -4.4   0.0         5.4      47.0       0.0        0.0   0.5      6   
1  1.0  -4.6   0.0         4.9      50.0       0.0        0.0   0.5      0   
2  1.0  -4.7   0.0         6.2      50.0       0.0        0.0   0.5      6   
3  1.0  -5.0   0.0         5.0      56.0       0.0        0.0   0.5      6   
4  1.0  -5.0   0.0         5.5      52.0       0.0        0.0   0.5      6   

   solar_power  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

# 데이터 표준화 (Standardization)

In [14]:
from sklearn.preprocessing import StandardScaler

df_SJ_st = StandardScaler().fit_transform(df_SJ)
df_SJ_st = pd.DataFrame(df_SJ_st,columns=df_SJ.columns)

In [15]:
df_SJ_st.head()

temp      rain  wind_speed  humidity  sun_hour  sun_power      snow  \
0 -1.653274 -0.096402    2.185007 -1.697738 -0.661259   -0.66238  0.452271   
1 -1.672671 -0.096402    1.864108 -1.539022 -0.661259   -0.66238  0.452271   
2 -1.682370 -0.096402    2.698445 -1.539022 -0.661259   -0.66238  0.452271   
3 -1.711466 -0.096402    1.928288 -1.221590 -0.661259   -0.66238  0.452271   
4 -1.711466 -0.096402    2.249187 -1.433211 -0.661259   -0.66238  0.452271   

      cloud  solar_power  
0  0.536202    -0.642665  
1 -0.951166    -0.642665  
2  0.536202    -0.642665  
3  0.536202    -0.642665  
4  0.536202    -0.642665

## 모든 열의 값이 1인 것 추가 (const)

In [16]:
one = np.ones((df_SJ_st.shape[0],1))
one = pd.DataFrame(one)

In [17]:
df_SJ_st1 = pd.concat([one,df_SJ_st],axis=1)
df_SJ_st1.head()

0      temp      rain  wind_speed  humidity  sun_hour  sun_power  \
0  1.0 -1.653274 -0.096402    2.185007 -1.697738 -0.661259   -0.66238   
1  1.0 -1.672671 -0.096402    1.864108 -1.539022 -0.661259   -0.66238   
2  1.0 -1.682370 -0.096402    2.698445 -1.539022 -0.661259   -0.66238   
3  1.0 -1.711466 -0.096402    1.928288 -1.221590 -0.661259   -0.66238   
4  1.0 -1.711466 -0.096402    2.249187 -1.433211 -0.661259   -0.66238   

       snow     cloud  solar_power  
0  0.452271  0.536202    -0.642665  
1  0.452271 -0.951166    -0.642665  
2  0.452271  0.536202    -0.642665  
3  0.452271  0.536202    -0.642665  
4  0.452271  0.536202    -0.642665

# 데이터 정규화 (Normalization)

In [18]:
from sklearn.preprocessing import MinMaxScaler

df_SJ_no =  MinMaxScaler().fit_transform(df_SJ)
df_SJ_no = pd.DataFrame(df_SJ_no,columns=df_SJ.columns)

In [19]:
df_SJ_no.head()

temp  rain  wind_speed  humidity  sun_hour  sun_power      snow  cloud  \
0  0.176596   0.0    0.490909      0.47       0.0        0.0  0.035461    0.6   
1  0.172340   0.0    0.445455      0.50       0.0        0.0  0.035461    0.0   
2  0.170213   0.0    0.563636      0.50       0.0        0.0  0.035461    0.6   
3  0.163830   0.0    0.454545      0.56       0.0        0.0  0.035461    0.6   
4  0.163830   0.0    0.500000      0.52       0.0        0.0  0.035461    0.6   

   solar_power  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0

## 모든 열의 값이 1인 것 추가 (const)

In [20]:
one = np.ones((df_SJ_no.shape[0],1))
one = pd.DataFrame(one)

In [21]:
df_SJ_no1 = pd.concat([one,df_SJ_no],axis=1)
df_SJ_no1.head()

0      temp  rain  wind_speed  humidity  sun_hour  sun_power      snow  \
0  1.0  0.176596   0.0    0.490909      0.47       0.0        0.0  0.035461   
1  1.0  0.172340   0.0    0.445455      0.50       0.0        0.0  0.035461   
2  1.0  0.170213   0.0    0.563636      0.50       0.0        0.0  0.035461   
3  1.0  0.163830   0.0    0.454545      0.56       0.0        0.0  0.035461   
4  1.0  0.163830   0.0    0.500000      0.52       0.0        0.0  0.035461   

   cloud  solar_power  
0    0.6          0.0  
1    0.0          0.0  
2    0.6          0.0  
3    0.6          0.0  
4    0.6          0.0

# 데이터 퍼지화 (Fuzzification)
- fuzzy로 이루어진 새로운 dataframe 만들기 (diff생성->dataframe)

## diff 함수 만들기

In [21]:
df_SJ.shape

(26303, 9)

In [22]:
def diff(df):
    diff = np.zeros((df.shape[0],df.shape[1]))
    for i in range(df.shape[0]):
        if(i != df.shape[0]-1):
            diff[i] = abs((df.iloc[i+1]-df.iloc[i])/2.)
        
        else:
            diff[i]= diff[i-1]
    
    return diff

## fuzzy 함수 만들기

In [23]:
def fuzzy(df):
    diff_df = diff(df)
    
    df_fuzz = np.transpose(np.array([df - diff_df, df, df + diff_df]),(1,2,0))
            
    return df_fuzz

## fuzzy_T 함수 만들기

In [24]:
def fuzzy_T(df):
    diff_df = diff(df)
    
    df_fuzz_T = np.transpose(np.array([df - diff_df, df, df + diff_df]))
            
    return df_fuzz_T

# 유의한 변수들 선택하기

In [25]:
import statsmodels.api as sm

def print_linear_reg(X, y):

    X2 = sm.add_constant(X)  
    model = sm.OLS(y, X2)
    fitted_model = model.fit()

    print(fitted_model.summary())

In [26]:
X = df_SJ_no.drop(['solar_power'],axis=1)
y = df_SJ_no[['solar_power']]

print_linear_reg(X,y)

                            OLS Regression Results                            
Dep. Variable:            solar_power   R-squared:                       0.921
Model:                            OLS   Adj. R-squared:                  0.921
Method:                 Least Squares   F-statistic:                 3.830e+04
Date:                Mon, 14 Mar 2022   Prob (F-statistic):               0.00
Time:                        00:26:48   Log-Likelihood:                 33449.
No. Observations:               26303   AIC:                        -6.688e+04
Df Residuals:                   26294   BIC:                        -6.681e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0047      0.003      1.706      0.0

# 회귀계수 구하기

## diamond 함수 정의 하기

In [27]:
def fuzzy_op(a,b):
    result = 0
    for i in range(len(a)):
        result += np.dot(a[i],b[i])
    return result

In [28]:
def diamond(a,b):
    b_T = np.transpose(b,(1,0,2))
    result = np.zeros((np.shape(a)[0],np.shape(b)[1]))
    for i in range(np.shape(a)[0]):
        for j in range((np.shape(b)[1])):
            result[i,j] = fuzzy_op(a[i],b_T[j])
    return result

# 매개분석 START !

## [crips] 정규화된 데이터 사용 (Normalization)

### (STEP1) 독립변수 - 매개변수

In [27]:
X = df_SJ_no.drop(['sun_power','solar_power'],axis=1)
m = df_SJ_no[['sun_power']]

print_linear_reg(X,m)

                            OLS Regression Results                            
Dep. Variable:              sun_power   R-squared:                       0.754
Model:                            OLS   Adj. R-squared:                  0.754
Method:                 Least Squares   F-statistic:                 1.151e+04
Date:                Mon, 14 Mar 2022   Prob (F-statistic):               0.00
Time:                        00:27:11   Log-Likelihood:                 19631.
No. Observations:               26303   AIC:                        -3.925e+04
Df Residuals:                   26295   BIC:                        -3.918e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1065      0.005     23.262      0.0

### (STEP2) 독립변수 - 종속변수

In [28]:
X = df_SJ_no.drop(['sun_power','solar_power'],axis=1)
y = df_SJ_no[['solar_power']]

print_linear_reg(X,y)

                            OLS Regression Results                            
Dep. Variable:            solar_power   R-squared:                       0.683
Model:                            OLS   Adj. R-squared:                  0.682
Method:                 Least Squares   F-statistic:                     8076.
Date:                Mon, 14 Mar 2022   Prob (F-statistic):               0.00
Time:                        00:27:12   Log-Likelihood:                 15162.
No. Observations:               26303   AIC:                        -3.031e+04
Df Residuals:                   26295   BIC:                        -3.024e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.1141      0.005     21.019      0.0

### (STEP3) 독립변수+매개변수 - 종속변수

In [29]:
X.m = df_SJ_no.drop(['solar_power'],axis=1)
y = df_SJ_no[['solar_power']]

print_linear_reg(X.m,y)

                            OLS Regression Results                            
Dep. Variable:            solar_power   R-squared:                       0.921
Model:                            OLS   Adj. R-squared:                  0.921
Method:                 Least Squares   F-statistic:                 3.830e+04
Date:                Mon, 14 Mar 2022   Prob (F-statistic):               0.00
Time:                        00:27:16   Log-Likelihood:                 33449.
No. Observations:               26303   AIC:                        -6.688e+04
Df Residuals:                   26294   BIC:                        -6.681e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0047      0.003      1.706      0.0

## [fuzzy] 정규화된 데이터 사용 (Normalization)

### (STEP1) 독립변수 - 매개변수

In [29]:
X_no = df_SJ_no1.drop(['sun_power','solar_power'],axis=1)
m_no = df_SJ_no1[['sun_power']]

In [30]:
X_no_fuzzy = fuzzy(X_no)
X_no_fuzzy_T = fuzzy_T(X_no)
m_no_fuzzy = fuzzy(m_no)

In [31]:
np.dot(np.linalg.inv(diamond(X_no_fuzzy_T,X_no_fuzzy)),diamond(X_no_fuzzy_T,m_no_fuzzy))

array([[ 0.10388678],
       [ 0.2083644 ],
       [-0.48655706],
       [ 0.13014934],
       [-0.25424055],
       [ 0.35015019],
       [ 0.06701723],
       [ 0.04718437]])

In [32]:
beta_X_to_m = np.ravel(np.dot(np.linalg.inv(diamond(X_no_fuzzy_T,X_no_fuzzy)),diamond(X_no_fuzzy_T,m_no_fuzzy)))
beta_X_to_m

array([ 0.10388678,  0.2083644 , -0.48655706,  0.13014934, -0.25424055,
        0.35015019,  0.06701723,  0.04718437])

### (STEP2) 독립변수 - 종속변수

In [33]:
X_no = df_SJ_no1.drop(['sun_power','solar_power'],axis=1)
y_no = df_SJ_no1[['solar_power']]

In [34]:
y_no_fuzzy = fuzzy(y_no)

In [35]:
np.dot(np.linalg.inv(diamond(X_no_fuzzy_T,X_no_fuzzy)),diamond(X_no_fuzzy_T,y_no_fuzzy))

array([[ 0.11211071],
       [ 0.24783213],
       [-0.58494541],
       [ 0.17042942],
       [-0.29065783],
       [ 0.31638586],
       [ 0.04277077],
       [ 0.05620097]])

In [36]:
beta_X_to_y = np.ravel(np.dot(np.linalg.inv(diamond(X_no_fuzzy_T,X_no_fuzzy)),diamond(X_no_fuzzy_T,y_no_fuzzy)))
beta_X_to_y

array([ 0.11211071,  0.24783213, -0.58494541,  0.17042942, -0.29065783,
        0.31638586,  0.04277077,  0.05620097])

### (STEP3) 독립변수+매개변수 - 종속변수

In [37]:
X.m_no = df_SJ_no1.drop(['solar_power'],axis=1)
y_no = df_SJ_no1[['solar_power']]

In [38]:
X.m_no_fuzzy = fuzzy(X.m_no)
X.m_no_fuzzy_T = fuzzy_T(X.m_no)

In [39]:
np.dot(np.linalg.inv(diamond(X.m_no_fuzzy_T,X.m_no_fuzzy)),diamond(X.m_no_fuzzy_T,y_no_fuzzy))

array([[ 0.00597489],
       [ 0.03495684],
       [-0.08785485],
       [ 0.03746247],
       [-0.03091321],
       [-0.04134475],
       [ 1.02164904],
       [-0.02569732],
       [ 0.0079951 ]])

In [40]:
beta_Xm_to_y = np.ravel(np.dot(np.linalg.inv(diamond(X.m_no_fuzzy_T,X.m_no_fuzzy)),diamond(X.m_no_fuzzy_T,y_no_fuzzy)))
beta_Xm_to_y

array([ 0.00597489,  0.03495684, -0.08785485,  0.03746247, -0.03091321,
       -0.04134475,  1.02164904, -0.02569732,  0.0079951 ])

# CI 구하기

## total effect 구하기

In [41]:
import statsmodels.api as sm

def linear_reg(X, y):
    X2 = sm.add_constant(X)  
    model = sm.OLS(y, X2)
    fitted_model = model.fit()
    return fitted_model

In [42]:
total_CMA = - 0.187
direct_CMA = - 0.120
indirect_CMA = -0.067

total_FMA = -0.043
direct_FMA = -0.105
indirect_FMA = 0.062

In [43]:
X.m_no = df_SJ_no.drop(['solar_power'],axis=1)
X.m_no_fuzzy = fuzzy(X.m_no)

In [44]:
n = len(X.m_no)

### CMA_total effect

In [45]:
### CSD, CSE 구하기 
# CSD = np.sqrt(((X.m_no - X.m_no.mean(axis=0))**2).sum()/(n-1))
# CSE = CSD / np.sqrt(n)

#pd.DataFrame((CSD,CSE),columns = X.m_no.columns,index = ['CSD','CSE'])

In [46]:
# CSE 구하기
CSE = linear_reg(X.m_no,y_no).bse[1:]# result.bse : OLS에서 회귀계수 표준오차
CSE

temp          0.002272
rain          0.043013
wind_speed    0.003453
humidity      0.003099
sun_hour      0.001889
sun_power     0.003647
snow          0.007176
cloud         0.001161
dtype: float64

In [47]:
### total effect 95% 신뢰구간

CI = pd.DataFrame((total_CMA - 1.96*CSE, total_CMA + 1.96*CSE),
             columns = X.m_no.columns,
             index = ['lower','upper'])

### z(t) & p-value
import scipy.stats as stats
ZP = pd.DataFrame((np.array(total_CMA/CSE), 2*stats.norm(0, 1).cdf(total_CMA/CSE)),
            columns = X.m_no.columns,
            index= ['z(t)','p-value'])

pd.concat([CI,ZP])

temp      rain  wind_speed   humidity   sun_hour  sun_power  \
lower    -0.191453 -0.271305   -0.193768  -0.193073  -0.190702  -0.194148   
upper    -0.182547 -0.102695   -0.180232  -0.180927  -0.183298  -0.179852   
z(t)    -82.317753 -4.347528  -54.154873 -60.349224 -99.014417 -51.276577   
p-value   0.000000  0.000014    0.000000   0.000000   0.000000   0.000000   

                  snow       cloud  
lower    -2.010648e-01   -0.189276  
upper    -1.729352e-01   -0.184724  
z(t)     -2.605935e+01 -161.047904  
p-value  1.054086e-149    0.000000

### FMA_total effect

In [48]:
### FSD, FSE 구하기 
FSD = np.sqrt(((X.m_no_fuzzy - X.m_no_fuzzy.mean(axis=0))**2).sum(axis=-1).sum(axis=0)/(n-1))
FSE = FSD/np.sqrt(n)

pd.DataFrame((FSD,FSE),columns = X.m_no.columns,index = ['FSD','FSE'])

temp      rain  wind_speed  humidity  sun_hour  sun_power      snow  \
FSD  0.380161  0.019019    0.247982  0.329269  0.734083   0.403607  0.104882   
FSE  0.002344  0.000117    0.001529  0.002030  0.004526   0.002489  0.000647   

        cloud  
FSD  0.721016  
FSE  0.004446

In [49]:
### total effect 95% 신뢰구간

CI = pd.DataFrame((total_FMA - 1.96*FSE, total_FMA + 1.96*FSE),
             columns = X.m_no.columns,
             index = ['lower','upper'])

### z(t) & p-value
import scipy.stats as stats
ZP = pd.DataFrame((np.array(total_FMA/FSE), 2*stats.norm(0, 1).cdf(total_FMA/FSE)),
            columns = X.m_no.columns,
            index= ['z(t)','p-value'])

pd.concat([CI,ZP])

temp        rain     wind_speed      humidity      sun_hour  \
lower   -4.759431e-02   -0.043230  -4.599691e-02 -4.697927e-02 -5.187153e-02   
upper   -3.840569e-02   -0.042770  -4.000309e-02 -3.902073e-02 -3.412847e-02   
z(t)    -1.834442e+01 -366.673084  -2.812230e+01 -2.117975e+01 -9.500052e+00   
p-value  3.658255e-75    0.000000  5.229337e-174  1.468018e-99  2.097858e-21   

            sun_power       snow         cloud  
lower   -4.787767e-02  -0.044268 -5.171361e-02  
upper   -3.812233e-02  -0.041732 -3.428639e-02  
z(t)    -1.727874e+01 -66.492140 -9.672223e+00  
p-value  6.801369e-67   0.000000  3.956878e-22

## direct effect 구하기

In [50]:
X_no = df_SJ_no.drop(['sun_power','solar_power'],axis=1)
X_no_fuzzy = fuzzy(X_no)

### CMA_direct effect

In [51]:
### CSD, CSE 구하기 
# CSD = np.sqrt(((X_no - X_no.mean(axis=0))**2).sum()/(n-1))
#CSD = np.std(X_no,ddof=1)
#CSE = CSD / np.sqrt(n)

#pd.DataFrame((CSD,CSE),columns = X_no.columns,index = ['CSD','CSE'])

In [52]:
# CSE 구하기
CSE = linear_reg(X_no,y_no).bse[1:]# result.bse : OLS에서 회귀계수 표준오차
CSE

temp          0.004308
rain          0.086093
wind_speed    0.006871
humidity      0.005923
sun_hour      0.002722
snow          0.014374
cloud         0.002294
dtype: float64

In [53]:
### total effect 95% 신뢰구간

CI = pd.DataFrame((direct_CMA - 1.96*CSE, direct_CMA + 1.96*CSE),
             columns = X_no.columns,
             index = ['lower','upper'])

### z(t) & p-value
import scipy.stats as stats
ZP = pd.DataFrame((np.array(direct_CMA/CSE), 2*stats.norm(0, 1).cdf(direct_CMA/CSE)),
            columns = X_no.columns,
            index= ['z(t)','p-value'])

pd.concat([CI,ZP])

temp      rain    wind_speed      humidity   sun_hour  \
lower    -1.284444e-01 -0.288742 -1.334666e-01 -1.316097e-01  -0.125335   
upper    -1.115556e-01  0.048742 -1.065334e-01 -1.083903e-01  -0.114665   
z(t)     -2.785283e+01 -1.393848 -1.746543e+01 -2.025897e+01 -44.083580   
p-value  9.953364e-171  0.163364  2.627081e-68  2.960911e-91   0.000000   

                 snow      cloud  
lower   -1.481737e-01  -0.124496  
upper   -9.182631e-02  -0.115504  
z(t)    -8.348213e+00 -52.311808  
p-value  6.930324e-17   0.000000

### FMA_direct effect

In [54]:
### FSD, FSE 구하기 
FSD = np.sqrt(((X_no_fuzzy - X_no_fuzzy.mean(axis=0))**2).sum(axis=-1).sum(axis=0)/(n-1))
FSE = FSD/np.sqrt(n)

pd.DataFrame((FSD,FSE),columns = X_no.columns,index = ['FSD','FSE'])

temp      rain  wind_speed  humidity  sun_hour      snow     cloud
FSD  0.380161  0.019019    0.247982  0.329269  0.734083  0.104882  0.721016
FSE  0.002344  0.000117    0.001529  0.002030  0.004526  0.000647  0.004446

In [55]:
### total effect 95% 신뢰구간

CI = pd.DataFrame((direct_FMA - 1.96*FSE, direct_FMA + 1.96*FSE),
             columns = X_no.columns,
             index = ['lower','upper'])

### z(t) & p-value
import scipy.stats as stats
ZP = pd.DataFrame((np.array(direct_FMA/FSE), 2*stats.norm(0, 1).cdf(direct_FMA/FSE)),
            columns = X_no.columns,
            index= ['z(t)','p-value'])

pd.concat([CI,ZP])

temp        rain  wind_speed   humidity       sun_hour  \
lower    -0.109594   -0.105230   -0.107997  -0.108979  -1.138715e-01   
upper    -0.100406   -0.104770   -0.102003  -0.101021  -9.612847e-02   
z(t)    -44.794508 -895.364507  -68.670735 -51.718000  -2.319780e+01   
p-value   0.000000    0.000000    0.000000   0.000000  4.791971e-119   

               snow          cloud  
lower     -0.106268  -1.137136e-01  
upper     -0.103732  -9.628639e-02  
z(t)    -162.364528  -2.361822e+01  
p-value    0.000000  2.504865e-123

## indirect effect 구하기

In [56]:
m_no = df_SJ_no[['sun_power']]
m_no_fuzzy = fuzzy(m_no)

### CMA

준비물 beta_a,cse_a,beta_b,cse_b

In [57]:
beta_a = linear_reg(X_no,m_no).params[1:]
beta_a

temp          0.201368
rain         -0.601276
wind_speed    0.113341
humidity     -0.255247
sun_hour      0.359836
snow          0.062921
cloud         0.053575
dtype: float64

In [58]:
cse_a = linear_reg(X_no,m_no).bse[1:]
cse_a

temp          0.003635
rain          0.072640
wind_speed    0.005797
humidity      0.004998
sun_hour      0.002297
snow          0.012128
cloud         0.001935
dtype: float64

In [59]:
beta_b = linear_reg(X.m_no,y_no).params[6]
beta_b

1.0271270268596289

In [60]:
cse_b = linear_reg(X.m_no,y_no).bse[6]
cse_b

0.003646889306440721

최종 CSE 구하기

In [61]:
CSE = np.sqrt(beta_a**2 * cse_b**2 + beta_b**2 * cse_a**2 +  cse_a**2 *  cse_b**2)
CSE

temp          0.003805
rain          0.074643
wind_speed    0.005969
humidity      0.005217
sun_hour      0.002699
snow          0.012459
cloud         0.001998
dtype: float64

In [62]:
### indirect effect 95% 신뢰구간

CI = pd.DataFrame((indirect_CMA - 1.96*CSE, indirect_CMA + 1.96*CSE),
             columns = X_no.columns,
             index = ['lower','upper'])

### z(t) & p-value
import scipy.stats as stats
ZP = pd.DataFrame((np.array(indirect_CMA/CSE), 2*stats.norm(0, 1).cdf(indirect_CMA/CSE)),
            columns = X_no.columns,
            index= ['z(t)','p-value'])

pd.concat([CI,ZP])

temp      rain    wind_speed      humidity       sun_hour  \
lower   -7.445840e-02 -0.213300 -7.869870e-02 -7.722542e-02  -7.229101e-02   
upper   -5.954160e-02  0.079300 -5.530130e-02 -5.677458e-02  -6.170899e-02   
z(t)    -1.760700e+01 -0.897605 -1.122517e+01 -1.284250e+01  -2.481945e+01   
p-value  2.176896e-69  0.369396  3.067806e-29  9.476451e-38  5.528902e-136   

                 snow          cloud  
lower   -9.142043e-02  -7.091526e-02  
upper   -4.257957e-02  -6.308474e-02  
z(t)    -5.377464e+00  -3.354054e+01  
p-value  7.554214e-08  1.236836e-246

### FMA

준비물 beta_a,cse_a,beta_b,cse_b

In [63]:
beta_a = beta_X_to_m[1:] #const 제외

In [64]:
### FSD, FSE 구하기_direct effect에서 가져옴
FSD = np.sqrt(((X_no_fuzzy - X_no_fuzzy.mean(axis=0))**2).sum(axis=-1).sum(axis=0)/(n-1))
FSE = FSD/np.sqrt(n)

In [65]:
fse_a = FSE

In [66]:
beta_b = beta_Xm_to_y[6]

In [67]:
### FSD, FSE 구하기_total effect에서 가져옴
FSD = np.sqrt(((X.m_no_fuzzy - X.m_no_fuzzy.mean(axis=0))**2).sum(axis=-1).sum(axis=0)/(n-1))
FSE = FSD/np.sqrt(n)

In [68]:
fse_b = FSE[6]

최종 FSE 구하기

In [69]:
FSE = np.sqrt(beta_a**2 * fse_b**2 + beta_b**2 * fse_a**2 +  fse_a**2 *  fse_b**2)
FSE

array([0.00239857, 0.00033669, 0.0015644 , 0.0020807 , 0.00462982,
       0.00066211, 0.00454207])

In [70]:
Z = indirect_FMA/FSE
Z

array([ 25.84871413, 184.14509062,  39.63171002,  29.79766035,
        13.3914417 ,  93.63955719,  13.65016558])

In [71]:
### indirect effect 95% 신뢰구간

CI = pd.DataFrame((indirect_FMA - 1.96*FSE, indirect_FMA + 1.96*FSE),
             columns = X_no.columns,
             index = ['lower','upper'])

### z(t) & p-value
import scipy.stats as stats

ZP = pd.DataFrame((np.array(indirect_FMA/FSE), 2*(1-stats.norm(0, 1).cdf(indirect_FMA/FSE))),
            columns = X_no.columns,
            index= ['z(t)','p-value'])

pd.concat([CI,ZP])

temp        rain  wind_speed   humidity   sun_hour       snow  \
lower     0.057299    0.061340    0.058934   0.057922   0.052926   0.060702   
upper     0.066701    0.062660    0.065066   0.066078   0.071074   0.063298   
z(t)     25.848714  184.145091   39.631710  29.797660  13.391442  93.639557   
p-value   0.000000    0.000000    0.000000   0.000000   0.000000   0.000000   

             cloud  
lower     0.053098  
upper     0.070902  
z(t)     13.650166  
p-value   0.000000